### ISSUE TITLE
An error when run get_face_feature_mxnet.py

### ISSUE THREAD

**Issue by kaishijeng** [becauseofAI/MobileFace#9]
Got the following error when run "python3 ./get_face_feature_mxnet.py"

/usr/local/lib/python3.5/dist-packages/mxnet-1.5.0-py3.5.egg/mxnet/module/base_module.py:55: UserWarning: You created Module with Module(..., label_names=['softmax_label']) but input with name 'softmax_label' is not found in symbol.list_arguments(). Did you mean one of:
        data
  warnings.warn(msg)
/usr/local/lib/python3.5/dist-packages/mxnet-1.5.0-py3.5.egg/mxnet/module/base_module.py:67: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[04:55:44] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v-209911.-80.-80. Attempting to upgrade...
[04:55:44] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
Traceback (most recent call last):
  File "./get_face_feature_mxnet.py", line 50, in <module>
    face_feature_extractor = MobileFaceFeatureExtractor(model_file, epoch, batch_size, context, gpu_id)
  File "./get_face_feature_mxnet.py", line 29, in __init__
    self.model.set_params(arg_params, aux_params)
  File "/usr/local/lib/python3.5/dist-packages/mxnet-1.5.0-py3.5.egg/mxnet/module/module.py", line 350, in set_params
    allow_extra=allow_extra)
  File "/usr/local/lib/python3.5/dist-packages/mxnet-1.5.0-py3.5.egg/mxnet/module/module.py", line 309, in init_params
    _impl(desc, arr, arg_params)
  File "/usr/local/lib/python3.5/dist-packages/mxnet-1.5.0-py3.5.egg/mxnet/module/module.py", line 300, in _impl
    raise RuntimeError("%s is not presented" % name)
RuntimeError: fc5_bias is not presented

**Comment by becauseofAI** [comment]
@kaishijeng 
Sorry for the late reply. I have fixed the bug. Now you can run it correctly.
